custombucket = "my-project-s3"
table = "intellipaat"
databasehost = "my-project-db.ctazesqiqf1w.us-east-1.rds.amazonaws.com"
duser = "vinod"
dpass = "drink7up"
s3database = "intellipaat"
kapp = "http://132.0.2.32:30008/"
